### ISSUE TITLE
Tracking implementation coverage for a customer use case

### ISSUE THREAD

**Issue by whummer** [localstack/snowflake-docs#43]
This issue helps tracking the implementation coverage for a specific use case of an early adopter / preview customer.

Required features and SQL functions (ticked off items are available in the `localstack/snowflake:latest` image):

- [x] `OBJECT_INSERT` - ✅
- [x] `OBJECT_CONSTRUCT` - ✅
- [x] `OBJECT_CONSTRUCT_KEEP_NULL` - ✅ 
- [x] `OBJECT_DELETE` - ✅
- [x] `OBJECT_KEYS` - ✅
- [x] `DATEDIFF` - ✅
- [x] `ROW_NUMBER` - ✅
- [x] `LATERAL FLATTEN` - ✅
- [x] `MERGE INTO` - ✅
- [x] `PARSE_JSON` - ✅
- [x] `COALESCE` - ✅ 
- [x] `MAX | HAVING | PARTITION BY` - ✅
- [x] `LAST_QUERY_ID` - ✅
- [x] `CURRENT_TIMESTAMP` - ✅
- [x] `UUID_STRING` - ✅
- [x] `GROUP BY HAVING` - ✅
- [x] `COPY INTO` (stages) - ✅
- [x] `FILE_FORMAT` - ✅
- [x] `ARRAY_SIZE` - ✅
- [x] `IS_NULL_VALUE`
- [x] `ARRAY_EXCEPT` - ✅
- [x] `USING` - ✅
- [x] `NVL` - ✅
- [x] `LEAST` - ✅ 
- [x] `GREATEST` - ✅
- [x] `CURRENT_TIMESTAMP` - ✅
- [x] `PARSE_IP` - ✅
- [x] `DATE_TRUNC` - ✅
- [x] `INITCAP`- ✅ 
- [x] `SPLIT`- ✅ 
- [x] `CONTAINS`- ✅
- [x] `ARRAY_TO_STRING`- ✅
- [x] `ARRAYS_OVERLAP`- ✅
- [x] `ARRAY_SLICE`- ✅
- [x] `ARRAY_CONTAINS`- ✅
- [x] `GET`- ✅
- [x] `TO_VARCHAR` - ✅
- [x] `FLATTEN` - `LATERAL JOIN` -  ✅
- [x] `HASH`- ✅
- [x] `CAST`- ✅
- [x] `DATEADD`- ✅
- [x] `IFF`- ✅
- [x] `CASE`- ✅
- [x] `NVL`- ✅
- [x] `NVL2`- ✅ 
- [x] `BETWEEN`- ✅ 
- [x] `ANY_VALUE`- ✅ 
- [x] `MODE`- ✅ 
- [x] `MIN`- ✅
- [x] `MIN_BY`- ✅ 
- [x] `MAX`- ✅
- [x] `MAX_BY`- ✅ 
- [x] `AVG`- ✅ 
- [x] `SUM`- ✅ 
- [x] `RANK`- ✅
- [x] `LAG`- ✅
- [x] `LEAD`- ✅
- [x] `data LOADING and UNLOADING` - ✅
- [x] `COPY INTO - STAGE EXTERNAL STORAGE`- ✅
- [x] `SHOW TABLES`- ✅

**Comment by Brijeshthummar02** [comment]
You can use a spreadsheet (Google Sheets, Excel) or a markdown document to track the features and their statuses.
